import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import React, { useState } from 'react';
import { ActivityIndicator, Alert, StatusBar as NativeStatusBar, Platform, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

export default function ExportScreen() {
  const router = useRouter();
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = () => {
    setIsExporting(true);
    setTimeout(() => {
      setIsExporting(false);
      Alert.alert("Export Success", "The complete statement CSV file has been sent to your registered email address.");
    }, 2000);
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar style="dark" />
      <View style={styles.header}>
        <TouchableOpacity style={styles.iconBtn} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={20} color="#1E293B" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Export Portfolio</Text>
        <View style={{ width: 40 }} />
      </View>

      <View style={styles.content}>
        <View style={styles.card}>
          <Ionicons name="cloud-download-outline" size={32} color="#3AA39F" style={{ marginBottom: 12 }} />
          <Text style={styles.cardTitle}>Statement CSV Ledger</Text>
          <Text style={styles.cardDesc}>Download all transaction logs, spend ratios, and wallet history generated by this account.</Text>
          
          <TouchableOpacity 
            style={[styles.exportBtn, isExporting && styles.disabledBtn]} 
            onPress={handleExport}
            disabled={isExporting}
          >
            {isExporting ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.exportBtnText}>Generate & Email Report</Text>}
          </TouchableOpacity>
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFBFD', paddingTop: Platform.OS === 'android' ? NativeStatusBar.currentHeight : 0 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, height: 60 },
  iconBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#EDF2F7' },
  headerTitle: { fontSize: 16, fontWeight: '600', color: '#1E293B' },
  content: { paddingHorizontal: 20, marginTop: 24 },
  card: { backgroundColor: '#FFFFFF', padding: 20, borderRadius: 20, borderWidth: 1, borderColor: '#F1F5F9', alignItems: 'center' },
  cardTitle: { fontSize: 16, fontWeight: '600', color: '#1E293B', marginBottom: 6 },
  cardDesc: { fontSize: 13, color: '#64748B', textAlign: 'center', lineHeight: 20, marginBottom: 20 },
  exportBtn: { backgroundColor: '#3AA39F', width: '100%', height: 48, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  exportBtnText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
  disabledBtn: { backgroundColor: '#CBD5E1' }
});